Apply updated bootstack template
canonical/charm-sosreport pull request #3
Opened 2023-03-27 09:50 UTC by chanchiwai-ray

Apply updated [bootstack template](https://code.launchpad.net/~bootstack-charmers/bootstack-charms-spec/+git/bootstack-charms-spec/+ref/master) at ee3294f3ec03bab8f24599ce3bc208e8fa9261d2.

List of check points:

- [ ] sonar-project.properties

2023-03-27 11:13 UTC, mkalcok approved these changes

2023-03-27 11:31 UTC, rgildein requested changes

2023-03-27 11:31 UTC, rgildein commented on .github/workflows/pr.yaml
> +      commands: "['FUNC_ARGS=\"--series jammy\" make functional']"
We had tests for bionic, focal and jammy In previous `func_tests.yaml` workflow, so I think we should stick with that. 
```suggestion
      commands: "['FUNC_ARGS=\"--series bionic\" make functional', 'FUNC_ARGS=\"--series focal\" make functional', 'FUNC_ARGS=\"--series jammy\" make functional']"
```

2023-03-27 13:17 UTC, esunar approved these changes
One small [issue](https://github.com/canonical/charm-sosreport/pull/3#discussion_r1149240434) with functional test otherwise LGTM

2023-03-27 13:28 UTC, esunar commented on .github/workflows/pr.yaml
> +      commands: "['FUNC_ARGS=\"--series jammy\" make functional']"
I agree since we have a lot of bionic clouds

2023-03-28 08:47 UTC, rgildein approved these changes
LGTM

2023-03-28 13:14 UTC, merged